### ISSUE TITLE
Getting fatal error while creating a ticket

### ISSUE THREAD

**Issue by Ganthimathi** [opendns/autotask-php#168]
Hi,

I have been trying the sample code (ticket_create_example.php) given in this forum  and getting the below mentioned error while generating the ticket. It's working fine till getting the zone information. Can I get some idea to come out of this fatal error?
Thanks in advance.

stdClass Object
(
    [getZoneInfoResult] => ATWS\AutotaskObjects\ATWSZoneInfo Object
        (
            [CI] => 513558
            [DataBaseType] => Pro
            [ErrorCode] => 0
            [URL] => https://webservices15.autotask.net/ATServices/1.5/atws.asmx
            [WebUrl] => https://ww15.autotask.net/
        )

)
Fatal error:  Uncaught SoapFault exception: [HTTP] Unauthorized in /var/www/html/autotask-php-0.3.2/src/Client.php:353
Stack trace:
#0 /var/www/html/autotask-php-0.3.2/src/Client.php(353): SoapClient->__doRequest('<?xml version="...', 'https://webserv...', 'http://autotask...', 1, 0)
#1 [internal function]: ATWS\Client->__doRequest('<?xml version="...', 'https://webserv...', 'http://autotask...', 1, 0)
#2 /var/www/html/autotask-php-0.3.2/src/Client.php(358): SoapClient->__soapCall('create', Array)
#3 /var/www/html/autotask-php-0.3.2/src/Client.php(231): ATWS\Client->_call('create', Array)
#4 /var/www/html/autotask-php-0.3.2/ticket_create.php(33): ATWS\Client->create(Object(ATWS\AutotaskObjects\Ticket))
#5 {main}
  thrown in /var/www/html/autotask-php-0.3.2/src/Client.php on line 353

**Comment by SirPoot-** [comment]
You are receiving the error message '[HTTP] Unauthorized'. The account you are using does not have access. Are you using an API Only Autotask Resource?
